# Numpy Library
- well documented library

In [1]:
import numpy as np

In [2]:
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [5]:
x = np.array([2,3,4,5]) #1D array
x2d = np.array([[1,2,3],[4,5,6]]) #2D array
x3d = np.array([[[1,2],[4,5]],[[2,1],[3,4]]]) #3D array
print(x)
print(x2d)
print(x3d)

[2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [4 5]]

 [[2 1]
  [3 4]]]


# Sequential Matrix
 - np.arange()
 - np.Linspace()

In [7]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [8]:
np.arange(0,10,2) #np.arange()

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,10,.2) #start stop step

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [12]:
#size
np.arange(0,10,.2).size

50

In [13]:
np.arange(0,10,.2).reshape(5,10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [17]:
np.linspace(0,15,4)

array([ 0.,  5., 10., 15.])

In [19]:
np.linspace(0,15,4).size

4

In [20]:
np.linspace(0,15,4).reshape(2,2)

array([[ 0.,  5.],
       [10., 15.]])

In [23]:
# randomized matrix with random number
# np.random.rand()
print(np.random.rand(3,3)) # 0 to 1

[[0.71751771 0.25486337 0.27890765]
 [0.77505773 0.27018589 0.83074976]
 [0.42550322 0.40338363 0.73719762]]


In [24]:
# np.random.randn(4,4) #normal distribution
print(np.random.randn(4,4)) #around 0

[[ 1.35164241 -1.91666694  0.50673179  1.89928358]
 [ 0.81054311 -1.18480344 -1.13868871  1.00048533]
 [-0.363629    0.96615402  0.99884279 -0.2426444 ]
 [-0.59825866  0.36809282  0.62721473 -0.09930999]]


In [25]:
# np.random.randint()
print(np.random.randint(-10,10,(3,3))) # random int from -10 to 10

[[-8  0  5]
 [-2  8  1]
 [-1  3  9]]


In [28]:
# np.random.uniform()
print(np.random.uniform(0,2,(3,3))) #random uniform from 0 to 10

[[1.95452689 0.94465571 0.65151777]
 [1.64043239 1.43438174 0.47807246]
 [1.20109078 0.12773542 0.43636256]]


In [27]:
# np.random.permutation()
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10])) #random permutation

[10  3  6  4  2  7  5  1  8  9]


In [31]:
xp = np.random.uniform(0,5,(3,3))
print(xp)
print(xp.astype(int))

[[0.76588563 2.15999692 0.90007938]
 [1.91238334 0.3328535  4.85354318]
 [3.70615797 4.34243022 1.10006383]]
[[0 2 0]
 [1 0 4]
 [3 4 1]]


# Operations

In [32]:
a = np.random.randint(-10,10,(3,3))
b = np.random.randint(-10,10,(3,3))
print(a)
print(b)

[[ -2  -6 -10]
 [-10  -9   4]
 [  2 -10   8]]
[[ 1  7 -8]
 [ 1 -9  3]
 [-9  7  5]]


In [33]:
# matrix and constant operations

a*10

array([[ -20,  -60, -100],
       [-100,  -90,   40],
       [  20, -100,   80]])

In [34]:
a % 10

array([[8, 4, 0],
       [0, 1, 4],
       [2, 0, 8]], dtype=int32)

In [35]:
a ** 2

array([[  4,  36, 100],
       [100,  81,  16],
       [  4, 100,  64]])

In [37]:
# same size matrix operations

print(a+b)

print(a-b)

print(a/b)

print(a*b)

print(a @ b)

[[ -1   1 -18]
 [ -9 -18   7]
 [ -7  -3  13]]
[[ -3 -13  -2]
 [-11   0   1]
 [ 11 -17   3]]
[[ -2.          -0.85714286   1.25      ]
 [-10.           1.           1.33333333]
 [ -0.22222222  -1.42857143   1.6       ]]
[[ -2 -42  80]
 [-10  81  12]
 [-18 -70  40]]
[[ 82 -30 -52]
 [-55  39  73]
 [-80 160  -6]]


In [39]:
# matrix multiplication
print(np.matmul(a,b))
print(np.dot(a,b))

[[ 82 -30 -52]
 [-55  39  73]
 [-80 160  -6]]
[[ 82 -30 -52]
 [-55  39  73]
 [-80 160  -6]]
